name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: site/package-lock.json
      
      - name: Install dependencies
        run: |
          cd site
          npm ci
      
      - name: Sync documentation
        run: |
          mkdir -p site/docs
          cp -r docs/* site/docs/ || true
      
      - name: Build website
        run: |
          cd site
          npm run build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/build
          force_orphan: true